name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Rust tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Run tests
        run: cargo test
